AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple API Endpoint configured using Swaggers specified inline and backed by a Lambda function
Resources:
## CCT API Definition.
  CCTApi:
    Type: AWS::Serverless::Api
    Properties:
        Name: CICDNodeApi
        StageName: dev
        DefinitionBody: 
            swagger: 2.0
            info:
              title: !Ref AWS::StackName
            paths:
                /:
                  get:
                    produces:
                    - application/json
                    responses:
                      '200':  
                        description: 200 response
                        schema:
                          $ref: "#/definitions/Empty"
                    security:
                    - myAPIsignin: []
                    x-amazon-apigateway-integration:
                      httpMethod: GET
                      type: aws
                      uri: arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:902849442700:function:cicdTestNode  :${stageVariables.version}/invocations
                      responses: 
                          default:
                            statusCode: "200"
                            responseParameters:
                              method.response.header.Access-Control-Allow-Origin: "'*'"
            securityDefinitions:
              myAPIsignin:
                type: "apiKey"
                name: "Authorization"
                in: "header"
                x-amazon-apigateway-authtype: "cognito_user_pools"
                x-amazon-apigateway-authorizer:
                  providerARNs:
                  - "arn:aws:cognito-idp:us-east-1:902849442700:userpool/us-east-1_Q3sA5af5A"
                  type: "cognito_user_pools"          

## Lambda function12.2
  CCTFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cicdTestNode
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /get
            Method: GET
            RestApiId: !Ref CCTApi