---
swagger: 2.0
info:
  title: !Ref AWS::StackName
paths:
    "/get":
        get:
        x-amazon-apigateway-integration:
            httpMethod: POST
            type: aws_proxy
            uri: arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:902849442700:function:CCTFunctionName:${stageVariables.version}/invocations
        responses: {}    