#/**
# @author: Rajeesh<rajeesh.k@iinerds.com> 
# @desc: The SAM template for building the CCT Backend API.
# @since: 2017-12-01
# */
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple API Endpoint configured using Swaggers specified inline and backed by a Lambda function
Resources:
  ## CCT API Definition.
  CCTApi:
    Type: AWS::Serverless::Api
    Properties:
        #/** API Name Need to be defined here. Place it after "Name:"
        # Please keep an unique name for API.
        # */
        Name: CICDNodeApi
        #/** 
        # It is compulsory to give a new Stage name. It is unused at this point of time.
        # By default the SAM template creates "Stage" stage, which is deleted by the 
        # API-HomeWork stage of CodePipeline.
        # */
        StageName: dev
        DefinitionUri: "./cct-sam-swagger.yml"
        Variables:
          # This is a circular reference as defined by SAM.
          LambdaFunctionName: !Ref CCTFunction

  ## Lambda function defined here.
  CCTFunction:
    Type: AWS::Serverless::Function
    Properties:
      #/**
      # Define the Lambda function name here; "FunctionName:<LambdaFunction>"
      # */
      FunctionName: cicdTestNode
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./
      Events:
        # This is a circular reference as defined by SAM.
        GetApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref CCTApi # Refer The API defined above.