AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple API Endpoint configured using Swaggers specified inline and backed by a Lambda function
Resources:
## API Definition - New.
  CCTApi:
    Type: AWS::Serverless::Api
    Properties:
        Name: CICDApi
        StageName: dev
        DefinitionBody: 
            swagger: 2.0
            info:
              title: !Ref AWS::StackName
            paths:
                "/":
                    get:
                    x-amazon-apigateway-integration:
                        httpMethod: GET
                        type: aws_proxy
                        uri: arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:902849442700:function:CICDTest:${stageVariables.version}/invocations
                    responses: {}
    Variables:
          CCTFunctionName: !Ref CCTFunction

## Lambda function12.2
  CCTFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CICDTest
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /get
            Method: GET
            RestApiId: !Ref CCTApi