AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple API Endpoint configured using Swaggers specified inline and backed by a Lambda function
Resources:
## API Definition.
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
        StageName: staging
        DefinitionBody:
            swagger: 2.0
            info:
              title:
                Ref: AWS::StackName
            paths:
              "/get":
                  get:
                   x-amazon-apigateway-integration:
                     httpMethod: POST
                     type: aws_proxy
                     uri: arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:902849442700:function:MyLambdaFunction:${stageVariables.version}/invocations
                   responses: {}
## Lambda function.
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyLambdaFunction
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./