AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple API Endpoint configured using Swaggers specified inline and backed by a Lambda function
Resources:
## API Definition - New.
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
        Name: CICDApi
        StageName: dev
        DefinitionUri: "./swagger.yaml"
## Lambda function12.2
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CICDFunction
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /get
            Method: GET
            RestApiId: !Ref MyApi