---
swagger: 2.0
basePath: /prod
info:
  title: AwsSamExample
schemes:
- https
    paths:
        "/get":
            get:
            x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:902849442700:function:CICDFunction:${stageVariables.version}/invocations
            responses: {}