  swagger: 2.0
  paths:
    /:
      x-amazon-apigateway-any-method:
        x-amazon-apigateway-integration:
          httpMethod: POST
          type: aws_proxy
            uri: arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:902849442700:${stageVariables.LambdaFunctionName}/invocations
          responses:
          default:
            statusCode: 200
